name: Build and Deploy

on: workflow_dispatch

jobs:
  build-server:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/echo8/pastesphere:latest
          file: Dockerfile.server
  
  deploy-server:
    runs-on: ubuntu-latest
    needs: build-server
    steps:
      - name: Deploy
        run: echo "foo"
  
  build-deploy-client:
    runs-on: ubuntu-latest
    needs: deploy-server
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build client
        run: npm run build:client
      
      - name: Deploy client
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/client/dist --project-name=pastesphere
